const ROUTING_PROVIDER = (process.env.ROUTING_PROVIDER || 'osrm').toLowerCase();
const ROUTING_API_BASE_URL =
  process.env.ROUTING_API_BASE_URL ||
  'https://router.project-osrm.org';
const ROUTING_PROFILE = process.env.ROUTING_PROFILE || 'driving';
const ROUTING_TIMEOUT_MS = Number(process.env.ROUTING_TIMEOUT_MS || 12000);

const OFF_ROUTE_THRESHOLD_METERS = Number(process.env.OFF_ROUTE_THRESHOLD_METERS || 120);
const OFF_ROUTE_REROUTE_COOLDOWN_MS = Number(
  process.env.OFF_ROUTE_REROUTE_COOLDOWN_MS || 30000
);
const OFF_ROUTE_REROUTE_MIN_MOVE_METERS = Number(
  process.env.OFF_ROUTE_REROUTE_MIN_MOVE_METERS || 45
);
const ACTIVE_SEGMENT_ROUTE_COOLDOWN_MS = Number(
  process.env.ACTIVE_SEGMENT_ROUTE_COOLDOWN_MS || 30000
);
const ACTIVE_SEGMENT_ROUTE_MIN_MOVE_METERS = Number(
  process.env.ACTIVE_SEGMENT_ROUTE_MIN_MOVE_METERS || 45
);

module.exports = {
  ROUTING_PROVIDER,
  ROUTING_API_BASE_URL,
  ROUTING_PROFILE,
  ROUTING_TIMEOUT_MS,
  OFF_ROUTE_THRESHOLD_METERS,
  OFF_ROUTE_REROUTE_COOLDOWN_MS,
  OFF_ROUTE_REROUTE_MIN_MOVE_METERS,
  ACTIVE_SEGMENT_ROUTE_COOLDOWN_MS,
  ACTIVE_SEGMENT_ROUTE_MIN_MOVE_METERS,
};
