const ACTIVE_TRIP_STATUSES = ['started', 'running', 'paused'];

const OFFLINE_THRESHOLD_SECONDS = Number(process.env.BUS_OFFLINE_THRESHOLD_SECONDS || 300);
const DELAY_THRESHOLD_MINUTES = Number(process.env.TRIP_DELAY_THRESHOLD_MINUTES || 5);
const MIN_ETA_SPEED_KMH = Number(process.env.MIN_ETA_SPEED_KMH || 18);
const STOP_ARRIVAL_RADIUS_METERS = Number(process.env.STOP_ARRIVAL_RADIUS_METERS || 80);

module.exports = {
  ACTIVE_TRIP_STATUSES,
  OFFLINE_THRESHOLD_SECONDS,
  DELAY_THRESHOLD_MINUTES,
  MIN_ETA_SPEED_KMH,
  STOP_ARRIVAL_RADIUS_METERS,
};
